### ISSUE TITLE
Group Settings

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#1]
## Value Statement
As a **user**
**I want** an edit button
**so that** I can update or change the details of the group

## Description
![Settings](https://github.com/jecaps/kris-kringle/assets/76426580/c976aec6-8983-4d05-88b6-b5048f27d018)

## Acceptance criteria
- [x] there should be an edit button
- [x] should be able to edit the group details
- [x] edit button should be hidden when editing is enabled
- [x] should show input fields when editing is enabled
- [x] should have a save and cancel button when editing is enabled

## Tasks
- [x] add a (Boolean) state that manages visibility of editing form
- [x] add a button 
  - [x] that triggers the state; with a pencil icon
- [x] add input fields for:
  - [x] group name
  - [x] budget
  - [x] date of exchange 
- [x] add a save button to save the changes in the database
- [x] add a cancel button that hides the editing form

## Size
medium
