### ISSUE TITLE
FE: Mobile first

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#13]
## Value Statement
As a **user**
**I want** to access this site from my phone
**so that** I can do changes to the group even when I am on the go.

## Description
![Mobile view](https://github.com/jecaps/kris-kringle/assets/76426580/df59dd45-b2f8-492d-804f-25dd972cebb0)

## Acceptance criteria
- [ ] there should be smaller fonts on smaller devices
- [ ] input fields and buttons should full length of screen

## Tasks
- [ ] change font sizes of titles and paragraphs
- [ ] add block display on input fields and buttons on smaller devices

## Size
large
