### ISSUE TITLE
FE: Password field for group access

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#17]
## Value Statement
As a **user**
**I want** only the group admin to have the access to assign santas, and update and delete group details and participants
**so that** other participants cannot manipulate other's entries.

## Acceptance criteria
- [x] 'Assign Santa' button, the group settings button, and the edit & delete participants buttons should only be visible to group admin
- [x] there should be a a field for the group password
- [x] there should be an error text shown when entered password is incorrect

## Tasks
- [x] add an input field for the group password on the area "Assign Santa" button is
- [x] add an error text when the password entered is incorrect

## Size
medium

**Comment by akanz1** [comment]
Works! 👍
