### ISSUE TITLE
BE: Password Encryption

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#18]
## Value Statement
As a **developer**
**I want** to implement password encryption
**so that** unauthorized access is prevented.

## Acceptance criteria
- [x] entered group passwords should be encrypted

## Tasks
- [x] install [Bcrypt](https://www.npmjs.com/package/bcrypt "Bcrypt")
- [x] implement password hashing that will be saved in the database when:
   - [x] creating group
   - [x] accessing group 
- [x] try to hash unhashed, existing group passwords

## Size
medium
