### ISSUE TITLE
Delete Group 

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#2]
## Value Statement
As a **user**
**I want** a delete group button 
**so that** I can delete the group that will no longer be used.

## Description
![Image](https://github.com/jecaps/kris-kringle/assets/76426580/3c436fe6-9a98-4a86-a1bf-a386055f647a)

![Image](https://github.com/jecaps/kris-kringle/assets/76426580/70031dd1-5098-4fdd-9172-97c7a60d7acb)

## Acceptance criteria
- [ ] there should be a delete button for the group 
- [ ] there should be a warning dialog when delete button is clicked 
- [ ] dialog should be closable
- [ ] user should be navigated to the home page when the deletion has been confirmed

## Tasks
- [ ] add a delete button
- [ ] create a (boolean) state that manages the visibility of the confirmation dialog
- [ ] add a confirmation dialog with a cancel and confirm button for the deletion

## Size
medium

**Comment by akanz1** [comment]
Works :)

---

But i've noticed budget can not be set to >=1000 else there is a server side issue
