### ISSUE TITLE
FE: Member Adding Enhancement

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#21]
## Value Statement
As a **user**
**I want** the pop up adding of a member to disappear upon submission
**so that** I do not have to manually close it.

## Description
![image](https://github.com/jecaps/kris-kringle/assets/76426580/205dc915-305b-46bf-aa6c-260643cc9cac)

## Acceptance criteria
- [ ] Adding group member dialog should disappear when the submit button is clicked
- [ ] There should be a toast instead to show that a certain member has been added to the group

## Tasks
- [ ] Remove code that shows text member is added
- [ ] Remove code that disables form fields when member is added
- [ ] Add toast that shows says member has been added

## Size
medium
