### ISSUE TITLE
FE: English & German Translations

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#23]
## Value Statement
As a **user**
**I want** to have buttons that changes the language of the page
**so that** my german friends can use it.

## Acceptance criteria
- [ ] there should be a button that toggles the language of the page
- [ ] the button should be on the top right of the page
- [ ] the button should indicate which language it is changing into
- [ ] default language should be english

## Tasks
- [ ] use next-i18next for translation
- [ ] use toggle button from Prime React

## Size
medium
