### ISSUE TITLE
Participant Settings

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#3]
## Value Statement
As a **user**
**I want** an edit button for each participant on the list
**so that** I update some details of a participant.

## Description
![EditButton](https://github.com/jecaps/kris-kringle/assets/76426580/28743403-d774-4a3c-bca6-162de4caea7a)

### Example for the pop up
![Overlay](https://github.com/jecaps/kris-kringle/assets/76426580/8d6110ce-ee67-435a-a6db-36e9bc1b2ca2)

## Acceptance criteria
- [x] there should be an edit button on the right side of each participant on the list
- [x] a pop up form for editing the participant nam, email, and wishlist should be shown on edit button click
- [x] pop up form should have a 'Edit Participant' heading
- [x] there should be a save and a cancel button the pop up form
- [x] pop up form should be hidden when the save or cancel button is clicked

## Tasks
- [x] add a button with a 'pi-pencil' icon on the right side of each participant
- [x] create a state that manages the visibility of the pop up form
- [x] create a form with:
  - [x] input fields for participant name and email
  - [x] labels for name, wishlist and email input fields
  - [x] a header with "Edit Participant" text
  - [x] a save button with a 'pi-save' icon
  - [x] a cancel button with a 'pi-times' icon

## Size
medium
