### ISSUE TITLE
Participant Deletion

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#5]
## Value Statement
As a **user**
**I want** an remove button for each participant on the list
**so that** I can remove participants that no longer wants to participate.

## Description
![Delete Participant](https://github.com/jecaps/kris-kringle/assets/76426580/3d825a94-ac98-4c45-96fc-c6754edf1fd0)

![confirmation pop up](https://github.com/jecaps/kris-kringle/assets/76426580/cdfaa622-c9c3-4354-8dd5-06ce6bea08a3)

## Acceptance criteria
- [x] there should be a button that removes a participant from the group
- [x] a confirmation pop should appear when the remove button is clicked
- [x] the confirmation pop up should have:
  - [x] a confirm button
  - [x] a cancel button 
- [x] the confirmation pop up should disappear when either cancel or confirm button has been clicked

## Tasks
- [x] create delete-participant.tsx in /components/participants
- [x] add a button with a "pi-trash" icon
- [x] use OverlayPanel for the participant deletion

## Size
small
