### ISSUE TITLE
Send Email to Participants

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#6]
## Value Statement
As a **user**
**I want** to receive an email with the name and wish list of my secret buddy
**so that** I know who I am giving a gift to and which gift to give.

## Acceptance criteria
- [x] an email should be sent to each participant once the 'Assign Secret Santa' button is clicked
- [x] email should contain **name & wish list** of the secret buddy
- [x] email text should be uniform to all participants **except** for the name and wish list 

## Tasks
- [x] create text to be sent to all participants

## Size
large
